### ISSUE TITLE
just_table doesn't work with drafts

### ISSUE THREAD

**Issue by rustyrazorblade** [burakkose/just_table#1]
Line 59 of just_table.py only looks at the articles list, but doesn't take drafts into account.  I changed my local copy to:

```
    for article in generator.articles + generator.drafts:
```

Drafts get a proper table this way.

**Comment by burakkose** [comment]
@rustyrazorblade , I missed that issue; It was my shame. Fortunately, @bosha have worked on that. Thank you for your feedback.
