### ISSUE TITLE
Not work in table with 2 rows

### ISSUE THREAD

**Issue by brunomacabeusbr** [burakkose/just_table#3]
For some reason, when I use

```
[jtable th="0"]
a,b
c,d
[/jtable]
```

I see
![image](https://cloud.githubusercontent.com/assets/9501115/24078339/ae8e363a-0c49-11e7-8d52-aa176477e883.png)

But, when I use

```
[jtable th="0"]
a,b
c,d
e,f
[/jtable]
```

Works!

![image](https://cloud.githubusercontent.com/assets/9501115/24078343/c1128c98-0c49-11e7-8865-a51dfbc03a9b.png)

**Comment by burakkose** [comment]
@brunomacabeusbr , thank you for your feedback. I will look into that.

**Comment by brunomacabeusbr** [comment]
Thank you so much =]
