### ISSUE TITLE
feature_request(usage): pages support

### ISSUE THREAD

**Issue by Kristinita** [burakkose/just_table#7]
### 1. Summary

It would be nice, if just_table will work [**in pages, not only in articles**](http://docs.getpelican.com/en/latest/content.html#articles-and-pages).

### 2. Argumentation

Pelican users may want use tables in pages.

### 3. Technical notes

You need add to `just_table.py` [**signals for pages**](http://docs.getpelican.com/en/latest/plugins.html#list-of-signals) as you add signals for articles.

[**Dirty, but working for pages `just_table.py`**](https://www.pastery.net/earrtq/).

Thanks.

**Comment by Kristinita** [comment]
@burakkose , ping.

See, how I make, that my Pelican plugin works [**for articles and pages both**](https://www.sports.ru/tribuna/blogs/festival/2450295.html):

```python
def run_plugin(generators):
    """Run plugin for different objects.

    Built by type summary.py pelican plugin:
    https://github.com/getpelican/pelican-plugins/blob/0b9e66ee7b0a3609c1d94e5aeb90144993a1603e/summary/summary.py#L94
    """
    for generator in generators:
        if isinstance(generator, ArticlesGenerator):
            # [INFO][PELICAN] All articles types:
            # https://github.com/getpelican/pelican/blob/8a769811377e2a3a32ba27b0a98e08f4102a0b43/pelican/generators.py#L289-L297
            for article in (generator.articles + generator.translations +
                            generator.drafts + generator.drafts_translations):
                putkiry(article)
        elif isinstance(generator, PagesGenerator):
            # [INFO][PELICAN] All pages types:
            # https://github.com/getpelican/pelican/blob/8a769811377e2a3a32ba27b0a98e08f4102a0b43/pelican/generators.py#L705-L710
            # [NOTE] generator.all_pages doesn't work
            for page in (generator.pages + generator.translations +
                         generator.hidden_pages + generator.hidden_translations +
                         generator.draft_pages + generator.draft_translations):
                putkiry(page)
```

Maybe it helps, and just_table will work for pages.

Thanks.

**Comment by burakkose** [comment]
Hey @Kristinita,

It looks like you’ve already solved the problem! Do you mind open a pull request so your code can live in the branch?

Best.

**Comment by Kristinita** [comment]
@burakkose, `type: reply`

I show example, what I do for [**my personal Pelican plugin**](https://github.com/Kristinita/KristinitaPelican/blob/master/personal-plugins/putkiry/putkiry.py) (for preserve paths) to make it work for articles and pages.

Sorry, I'm not a programmer — I'm not sure, that I can do it for just_table.

But [**this version**](https://www.pastery.net/earrtq/) `just_table.py` with code duplicates successful works for articles and pages both.

Thanks.

**Comment by wumpus** [comment]
Thank you for this, I was wondering why just tables wasn't working on my website, which is 100% pages.
